### ISSUE TITLE
Using resulting forcefield

### ISSUE THREAD

**Issue by jthorton** [openforcefield/openff-bespokefit#111]
After a user submits an optimisation using `openff-bespoke executor run` they will get a json output file which is a serialised [CoordinatorGetResponse](https://github.com/openforcefield/openff-bespokefit/blob/27b072bd09610dc8209429118d739e1f453edd61/openff/bespokefit/executor/services/coordinator/models.py#L72) object which does contain the final refit force field but is awkward to get to and involves something like

```python
from openff.qcsubmit.serializers import deserialize
from openff.bespokefit.schema.results import BespokeOptimizationResults

data = deserialize("output.json")
result = BespokeOptimizationResults.parse_obj(data["results"])
force_field = result.refit_force_field
```

Maybe we should add a CLI entry point to extract the force field quickly from a result and write out the offxml file, something like
`openff-bespoke result extract <output.json> new_ff.offxml`
It might also then make sense to have a command which can combine multiple outputs to a single force field, like in the case of parametrising a congeneric series for binding free energy calculations which require a single input force field this could be
`openff-bespoke result combine <list of results>. new_ff.offxml`.

**Comment by Yoshanuikabundi** [comment]
We could also have an optional argument like `--forcefield ff_out.offxml` that lets users specify a file that the force field is written to. If the argument isn't specified then we just behave like at present.

CLI tools for parsing results definitely seems like a good idea to me. If we named `result extract` something like `extract forcefield` then the interface would generalise nicely to being able to extract other results easily, which is probably worthwhile. Then `result combine` could be `combine forcefield`. My only concern would be that combine would have ambiguous and possibly incorrect results if the results had clashing terms, so we should probably error out (with an optional override) if that happens.

**Comment by jthorton** [comment]
Great ideas, I really like the idea of structuring the extract like that so we can add more options in future! 

> My only concern would be that combine would have ambiguous and possibly incorrect results if the results had clashing terms, so we should probably error out (with an optional override) if that happens.

Yeah, I totally agree I am currently testing this to see how often we get clashes in a congeneric series, but an error is definitely the safe way to go.

**Comment by Yoshanuikabundi** [comment]
Ok ran into this again trying to document reading results - I think it would be great to have at least `from_file` implemented on `CoordinatorGETResponse` so that people can pull it back into python world. One simple way to do this would be to move the `from_file` and `to_file` methods from `BespokeWorkflowFactory` to `SchemaBase` -  I think their implementations are already generic enough for this!

**Comment by SimonBoothroyd** [comment]
> I think it would be great to have at least `from_file`

Is the idea to have `from_file` in addition to the built-in `parse_file` method?

**Comment by Yoshanuikabundi** [comment]
Yes - I couldn't get `parse_file` to work, I think because [`BespokeWorkflowFactory.to_file`](https://github.com/openforcefield/openff-bespokefit/blob/d52f6963d0fe9ac957de4e1f285e2d43dbc6d7a6/openff/bespokefit/workflows/bespoke.py#L210-L221) uses the QCSubmit serializer, not the pydantic one. Admittedly I did give up very quickly.
