### ISSUE TITLE
Pin celery version in c-f recipe.

### ISSUE THREAD

**Issue by jthorton** [openforcefield/openff-bespokefit#131]
installing bespokefit and psi4 via `mamba create -n bespoke  psi4 openff-bespoke -c psi4 -c defaults` solves to a celery version which is too old. We need to pin to at least 5.2.1 in the recipe.

**Comment by SimonBoothroyd** [comment]
I think the issue here is that new versions of `celery` require a new version of `click`, whereas `click-option-group` currently pins to an old version of `click` leading to incompatibilities. I'm trying to get this resolved [in the feedstock](https://github.com/conda-forge/click-option-group-feedstock)

**Comment by jthorton** [comment]
Ahh yes that makes sense although I am not sure why mamba solved the above with `celery=4.4.0` when `5.1.2` is also compatible and actually works? Maybe we could add some temporary pins, for now, util this is fixed in `click-option-group`?

**Comment by SimonBoothroyd** [comment]
Sure we can definitely give that a go! I remember getting package conflicts when I was trying that before, but I may haven't gotten the pins quite right 🙁

**Comment by SimonBoothroyd** [comment]
Fixed by https://github.com/conda-forge/openff-bespokefit-feedstock/pull/2/files
