### ISSUE TITLE
Command to reproduce the tweet

### ISSUE THREAD

**Issue by xiki-tempula** [openforcefield/openff-bespokefit#175]
Congratulations, it is nice to see the exciting new result in https://twitter.com/ColeGroupNCL/status/1526871422798266371?s=20&t=dDinH7MFq9w5r6nQTjYs7g.
I wonder if I could have the command to reproduce this force field, I guess it is `openff-bespoke executor run --file "lig.sdf" --workflow "default" --output "lig.json" --output-force-field "lig.offxml" --default-qc-spec psi4 B3LYP-D3BJ DZVP`?

**Comment by jthorton** [comment]
Thanks @xiki-tempula, this work used the default workflow so no need to add the `--default-qc-spec` flag the `--workflow default` part includes the Psi4 information, the full default workflow settings file can be found [here](https://github.com/openforcefield/openff-bespokefit/blob/main/openff/bespokefit/data/schemas/default.json) for reference.

**Comment by xiki-tempula** [comment]
@jthorton Sorry, I don't quite understand 

> this work used the default workflow so no need to add the --default-qc-spec flag the --workflow default part includes the Psi4 information

Do you mean that in this specific case where I'm using B3LYP-D3BJ/DZVP there is no need for `--default-qc-spec psi4 B3LYP-D3BJ DZVP` and `openff-bespoke executor run --file "lig.sdf" --workflow "default" --output "lig.json" --output-force-field "lig.offxml"` will do the same thing?

Or when I select `--workflow default`, `--default-qc-spec` will be ignored as -`-workflow default part includes the Psi4 information`?

Another slightly irrelevant question, I had an initial try of openff-bespokefit 0.1.0, do the newest 0.1.2 contains bug fix so the precious results should be treated with caution? Sorry, I know this is semantic version so this should be a bug fix update but I just want to be sure.

**Comment by jthorton** [comment]
> Do you mean that in this specific case where I'm using B3LYP-D3BJ/DZVP there is no need for --default-qc-spec psi4 B3LYP-D3BJ DZVP and openff-bespoke executor run --file "lig.sdf" --workflow "default" --output "lig.json" --output-force-field "lig.offxml" will do the same thing?

That is correct the default workflow already contains the information in `--default-qc-spec` flag. 

>I had an initial try of openff-bespokefit 0.1.0, do the newest 0.1.2 contains bug fix so the previous results should be treated with caution?

0.1.2 has bug fixes not related to torsion fitting so your results from 0.1.0 should be consistent with what you get from 0.1.2.

**Comment by xiki-tempula** [comment]
@jthorton Thanks for the help. I wonder if the ligand topology used in the tweet could be shared as well? I have made my topology using the same method but my result is not as good as the one mentioned in the tweet. It would be nice if I could have your ligand topology so I could check if it is due to that I generated the topology wrongly or it is my free energy calculation that is wrong.

**Comment by djcole56** [comment]
Hi @xiki-tempula, thanks for your interest. Just to clarify, your post linked to the free energy calculations plot for TYK2, is that what you wanted to reproduce? That's quite an intensive calculation, we'll distribute all the force fields and protocols used there, but it will take us a few more weeks to put all the data together for a paper. If you just meant the potential energy surface in my second tweet, that should be easier to reproduce and @jthorton can probably continue to advise.

**Comment by xiki-tempula** [comment]
@djcole56 

> your post linked to the free energy calculations plot for TYK2, is that what you wanted to reproduce? 

yes

So we used openff-bespokefit/B3LYP-D3(BJ)/DZVP to generate the TYK2 ligand force field and pass it to our own RBFE pipeline. Our openff-bespokefit RBFE result is worse than the openFF passed through the same pipeline, so I was hoping to get your ligand topology file so as to check if it is the issue that we didn't generate the ligand topology correctly.

**Comment by djcole56** [comment]
Oh I see, that's impressively fast! Yes, we should be able to check out these ligand FFs and get back to you.

**Comment by jthorton** [comment]
Hi @xiki-tempula thanks for sharing your BespokeFit files, to double-check the results of your fitting I ran molecule `lig_jmc_28` through BespokeFit fitting to the cached torsion scans I ran earlier on QCArchive in the torsion drive dataset named `OpenFF-benchmark-ligand-fragments-v2.0`. I get precisely the same SMIRKS patterns and a very similar final force field to the one you supplied, there are some slight differences due to the slightly different QM reference data but this is to be expected, see the force field file attached. 

I have also used BespokeFit to [combine](https://docs.openforcefield.org/projects/bespokefit/en/stable/users/bespoke-results.html#combining-force-fields) all of the force fields you sent to a single version (see attached combined.offxml.txt) and used this to benchmark the performance of your parameters by calculating the RMSE between my QCArchive QM reference data and your force field across all of the TYK2 torsiondrives compared to just sage and see an improvement as expected so it seems that the force fields you have produced are correct.
| Force Field       | Average RMSE kcal/mol |
|-------------------|-----------------------|
| Sage              | 1.069                 |
| BespokeFit + Sage | 0.404                 |


Its also worth mentioning that the force field I made for the RBFE made use of the caching in BespokeFit where parameters derived for one fragment can be re-used if BespokeFit sees the same fragment again. In the case of TYK2 there is a common core fragment as highlighted in the docs at the bottom of [this section](https://docs.openforcefield.org/projects/bespokefit/en/stable/users/theory.html#torsion-smirks). So I submitted the molecules one at a time to BespokeFit to ensure the parameters were reused meaning all of the molecules have consistent core parameters during fitting. This also means they are consistent when combined into a single force field which we needed to work with our protocol based on PMX. Our results are also based on `openff-1.3.0` as sage was not available when we started testing which may explain another difference. 

Are you able to share your statistics for the RBFE calculations with both sage and the bespoke version we would be very interested to see the results compared to what we have calculated for `openff-1.3.0`.

To confirm our input SDF files for the ligands are taken from [here](https://github.com/openforcefield/protein-ligand-benchmark/tree/main/data/2020-02-07_tyk2/02_ligands) and seem identical to yours. 
[jmc_28.offxml.txt](https://github.com/openforcefield/openff-bespokefit/files/8729702/jmc_28.offxml.txt)
[combined.offxml.txt](https://github.com/openforcefield/openff-bespokefit/files/8729710/combined.offxml.txt)

**Comment by xiki-tempula** [comment]
@jthorton Please find the ddG of each edge attached.
|   edge           |   Bespokenfit           |   Sage   |   Exp ddG  |
|------------------|-------------------------|----------|------------|
|   ejm_31_ejm_43  |   -0.2568780408781540   |   1.61   |   1.29     |
|   ejm_31_ejm_45  |   -1.2062618834269300   |   -0.2   |   -0.01    |
|   ejm_31_ejm_46  |   -3.0881167961646300   |   -0.79  |   -1.77    |
|   ejm_31_ejm_48  |   -1.0292116007341900   |   0.92   |   0.54     |
|   ejm_31_jmc_28  |   -3.693951630003490    |   -0.66  |   -1.43    |
|   ejm_42_ejm_48  |   0.04055860735068490   |   0.55   |   0.78     |
|   ejm_42_ejm_54  |   -2.2269856491034100   |   -1.05  |   -0.75    |
|   ejm_42_ejm_55  |   -1.507158763344570    |   -1.07  |   0.58     |
|   ejm_43_ejm_55  |   -1.7692586851890400   |   -2.03  |   -0.95    |
|   ejm_44_ejm_42  |   -1.7015084994310900   |   -2.31  |   -2.37    |
|   ejm_44_ejm_55  |   -3.208667262775650    |   -3.38  |   -1.79    |
|   ejm_45_ejm_42  |   0.13649167534203600   |   0.46   |   -0.23    |
|   ejm_47_ejm_31  |   1.614724007703100     |   -0.2   |   0.15     |
|   ejm_47_ejm_55  |   -0.41141271836408400  |   -0.62  |   0.49     |
|   ejm_49_ejm_31  |   0.7302436763757800    |   -0.81  |   -1.8     |
|   ejm_49_ejm_50  |   0.21300805335601500   |   -0.4   |   -1.23    |
|   ejm_50_ejm_42  |   -0.552534585065128    |   -0.13  |   -0.81    |
|   ejm_55_ejm_54  |   -0.7198268857588450   |   0.1    |   -1.33    |
|   jmc_23_ejm_46  |   0.8311279903414640    |   0.25   |   0.39     |
|   jmc_23_ejm_55  |   1.8931080604389000    |   0.6    |   2.5      |
|   jmc_23_jmc_27  |   0.1125089451591740    |   -0.24  |   0.42     |
|   jmc_23_jmc_30  |   -0.28726534873978900  |   -0.61  |   0.77     |
|   jmc_28_jmc_27  |   -0.11278421134342700  |   -0.6   |   -0.31    |
|   jmc_28_jmc_30  |   -0.5125585052424230   |   -0.97  |   0.04     |

**Comment by xiki-tempula** [comment]
@jthorton Thank you. This makes sense but I had some question with regard to the procedure. Sorry if I'm wrong that I haven't had a close look at the code itself.

My impression is that for example that we have molecule of congeneric series. The molecule alpha that has some torsions, A-B-C-D. 

The bespokenfit generate the data for the two fragments, A-B-C and B-C-D. 
Then use force balance to fit all dihedrals together using information from fragment from both A-B-C and B-C-D. In this sense, the torsion B-C contains information from both A-B-C and B-C-D.

Then we go for another molecule that is A-B-C-E.
The molecule is fragmented into A-B-C and B-C-E. The calculation for A-B-C is skipped.
Then force balance fits all dihedrals together where B-C is fitted taking into information from both A-B-C and B-C-E.

Then how do you derive the single parameter for B-C in `openff-bespoke executor combine`? As the B-C from first molecule will absorb some error for the B-C-D fragments and B-C from second molecule will absorb some error for the B-C-E fragments? Thank you.

**Comment by xiki-tempula** [comment]
We manage to get good results now so I will close this issue.

**Comment by jthorton** [comment]
Thanks @xiki-tempula are you able to share what changed in your setup to get better results it might be a good idea to add a guide on best use practices and free energy calculations using BespokeFit force fields.

**Comment by xiki-tempula** [comment]
I don't know TBH, but I think it is more like start with openFF 2.0 will give worse result than start with openFF 1.3. Where openFF 1.3 will do better on our pipeline as well compared to openFF 2.0.
