### ISSUE TITLE
Install xTB using MKL backend

### ISSUE THREAD

**Issue by xiki-tempula** [openforcefield/openff-bespokefit#180]
Would it be better to update the doc to install MKL as the backend for xTB so that parallelisation could work better?
related https://github.com/grimme-lab/xtb/issues/401

**Comment by j-wags** [comment]
This could be a good idea, however we should tread carefully with respect to licenses - OpenFF has pretty strict open-source requirements and our software needs to be free for anyone to use with no licensing entanglements for commercial use. 

I've found the intel MKL license [here](https://www.intel.com/content/dam/develop/external/us/en/documents/pdf/intel-simplified-software-license-version-august-2021.pdf) and some friendly-looking Q&A [here](https://www.intel.com/content/www/us/en/developer/articles/license/onemkl-license-faq.html) which seem quite permissive at a glance. 

Does anyone feel confident saying that there's no risk here? Right now I'd propose hedging our bets and updating the docs to say something like "you can probably get xTB to run faster by using a better mkl library, but be aware that they may have different license agreements"

**Comment by mattwthompson** [comment]
I could use some clarification on how exactly this package interacts with XTB, since I've only ever installed the [Python _wrapper_ ](https://github.com/grimme-lab/xtb-python), not a standalone `xtb` package. In any case, we're not shipping `xtb`, `xtb-python`, or anything else with the [conda package](https://github.com/conda-forge/openff-toolkit-feedstock/blob/main/recipe/meta.yaml) so license barriers aren't fundamentally different than our normal OpenEye use.

I'd be in support of adding some sort of informative one-liner about how users could install an MKL variant if they wished, but I think much more than that might be out of our hands.

Anyway, I've been of the understanding that we're generally advising Psi4 for production ... ?

**Comment by jthorton** [comment]
@xiki-tempula great idea I think any advice we can give users on making the installation easier to get the best performance will save future issues. So if @j-wags and @mattwthompson you are happy that this is in the same realm as the Openeye license then lets modify the install command or add an extra section on it?

@mattwthompson good point we are advising the use of Psi4 in production however we have been investigating the use of faster methods like xTB as a full replacement or how it could be used to speed up the data generation process such as pre-optimising conformers before QM. I believe the xtb-python pulls in xtb as part of the conda install so this should help many users who want to try xtb.

**Comment by mattwthompson** [comment]
Thanks @xiki-tempula for finding this and suggesting this change! It is now in the quickstart guide.
