### ISSUE TITLE
Issue when running with psi4 - installation problem?

### ISSUE THREAD

**Issue by simonlichtinger** [openforcefield/openff-bespokefit#183]
Dear bespoke fit devs,

### System and Installation details

Running on Ubuntu 18.04 LTS.
Created a fresh python 3.9 environment, and then installed as by the instructions in https://docs.openforcefield.org/projects/bespokefit/en/latest/getting-started/installation.html 

```
conda create -n bespokefit_2 python=3.9
conda activate bespokefit_2
conda install -c conda-forge openff-bespokefit
conda install -c openeye openeye-toolkits
conda install -c conda-forge -c defaults -c psi4 psi4
```

### Steps to reproduce and observed behaviour

The following molecule
[ala-ala.sdf.zip](https://github.com/openforcefield/openff-bespokefit/files/8853949/ala-ala.sdf.zip)

was run with this command:
```
openff-bespoke executor run --file  "ala-ala.sdf"  --workflow  "default" --n-fragmenter-workers 2 --n-optimizer-workers  2  --n-qc-compute-workers 2 --qc-compute-n-cores   4 
```

It progresses through fragmentation, but at the quantum generation part, after a few seconds, throws this error: 

[...] 
```
File                                                                               
 \"/biggin/b197/sjoh5255/anaconda3/envs/bespokefit_2/lib/python3.9/site-packages/qcengine/programs/psi4.py\", line 91, in           
 get_version\n    self.version_cache = safe_version(exc[\"stdout\"].split()[-1])\nIndexError: list index out of range\n\n\n"

```

Full traceback in the output.json file:
[output.zip](https://github.com/openforcefield/openff-bespokefit/files/8853984/output.zip)

### What else I've tried

* The molecule is processed correctly by other openff packages.
* Everything runs fine with xtb.

### Conlcusion

This seems to be an installation issue, but I couldn't find any guidance regarding this specific issue in either the documentation or other issues here. Is the recommended way of installing bespokefit + openeye + psi4 something different? If so, what is it?

Many thanks
Simon

**Comment by mattwthompson** [comment]
Hi @simonlichtinger thanks for the through report. The way you installed everything looks fine to me. The error appears to be raised from QCEngine doing a version check via a [wrapped call](https://github.com/MolSSI/QCEngine/blob/c171e80c51afc5bc08ac8a84971b526fd33671d3/qcengine/programs/psi4.py#L87-L91) to `psi4 --version` - what happens if you run `psi4 --version` directly?

**Comment by simonlichtinger** [comment]
Thanks for the quick reply. When I try to run the version check, I get:

```
Traceback (most recent call last):
  File "/biggin/b197/sjoh5255/anaconda3/envs/psi4_2/bin/psi4", line 188, in <module>
    import psi4  # isort:skip
  File "/biggin/b197/sjoh5255/anaconda3/envs/psi4_2/lib//python3.9/site-packages/psi4/__init__.py", line 54, in <module>
    from . import core
ImportError: libecpint.so.1: cannot open shared object file: No such file or directory
```

I have also done some further tests, and it appears the issue is specifically with psi4 obtained from the conda-forge channel.
Running `conda update psi4 -c psi4` appears to fix the issue, and in fact making a new environment with just psi4 works if installing from the psi4 channel, but doesn't when installing form conda-forge.

No idea why this is, but presumably it's not your issue. Maybe you could test to see if you can reproduce this and if so add a note to the documentation?

**Comment by mattwthompson** [comment]
> issue is specifically with psi4 obtained from the conda-forge channel

I assume you mean some dependencies and not `psi4` itself, because I can't find it. I know some of its upstreams only work when grabbed from the `psi4` channel, but don't know much more than that. What you found (installing it again without exposing it to `conda-forge`) is something we see a lot.

Probably the important detail when installing with a one-liner or making a fresh environment is the channel priority - I notice the [one-liner](https://github.com/openforcefield/openff-bespokefit/issues/162#issuecomment-1108753510) I go back to a lot has a different channel priority than what we've listed in the docs and this is probably why you ran

```
$ conda install -c conda-forge -c defaults -c psi4 psi4
```

vs.
```
conda install -c psi4 -c conda-forge -c defaults psi4
```

which I'd expect to be the root cause of the issue you've found. I'll see if I can reproduce this as expected.

**Comment by pavankum** [comment]
Just putting this out there if it helps: 
I had installed bespokefit with psi4 1.5 on linux (ubuntu) before and it worked well with this, `mamba create -n bespokefit -c psi4 -c conda-forge -c defaults python=3.9 openff-bespokefit psi4 ambertools "h5py<3.2"`. And the versions I have are

psi4 1.5+e9f4d6d  py39hbf93d9d_0    psi4

libint2  2.6.0  hc9558a2_9  psi4
  
(It is possible though that there might be some version clashes with libint2 in the new releases even if you pin psi4 to 1.5, Lori suggested selecting a libint2 version here https://github.com/psi4/psi4/issues/2593#issuecomment-1145503791, which is same as above in my env. )

**Comment by mattwthompson** [comment]
I notice when `psi4` is listed as the **last** channel, `libecpint` is pulled from `conda-forge`:


```
(bespokefit_2) [openff-bespokefit] CONDA_SUBDIR=osx-64 mamba install psi4 -c conda-forge -c defaults -c psi4

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.22.1) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['psi4']

pkgs/main/noarch                                   810.1kB @   1.1MB/s  0.8s
psi4/noarch                                          4.2kB @   3.2kB/s  0.5s
pkgs/r/osx-64                                      821.8kB @ 577.6kB/s  1.4s
pkgs/main/osx-64                                     4.3MB @   2.4MB/s  1.9s
pkgs/r/noarch                                      495.9kB @ 263.3kB/s  0.6s
psi4/osx-64                                         28.7kB @  15.1kB/s  0.5s
conda-forge/noarch                                   8.4MB @   2.4MB/s  3.8s
conda-forge/osx-64                                  21.4MB @   2.3MB/s 10.1s

Pinned packages:
  - python 3.9.*


Transaction

  Prefix: /Users/mattthompson/miniconda3/envs/bespokefit_2

  Updating specs:

   - psi4
   - ca-certificates
   - certifi
   - openssl


  Package          Version  Build           Channel                 Size
──────────────────────────────────────────────────────────────────────────
  Install:
──────────────────────────────────────────────────────────────────────────

  + ambit              0.6  py39h23e7102_2  psi4/osx-64            429kB
  + chemps2         1.8.11  h7778601_0      psi4/osx-64            782kB
  + dftd3            3.2.1  h4f947d3_1      psi4/osx-64            426kB
  + dkh                1.2  h97561c3_4      psi4/osx-64             35kB
  + gau2grid         2.0.7  haf1e3a3_0      psi4/osx-64            286kB
  + gcp              2.0.2  h0e1e685_0      psi4/osx-64             91kB
  + gdma             2.2.6  h97561c3_6      psi4/osx-64            182kB
  + libecpint        1.0.7  py39h9fcab8e_1  conda-forge/osx-64     403kB
  + libint2          2.6.0  h879752b_7      psi4/osx-64             71MB
  + libxc            5.1.5  haf1e3a3_0      psi4/osx-64              3MB
  + pcmsolver      1.2.1.1  py39h23dd00a_0  psi4/osx-64            694kB
  + psi4       1.6+77475b5  py39h4367506_0  psi4/osx-64             28MB
  + pugixml         1.11.4  he49afe7_0      conda-forge/osx-64     107kB
  + simint             0.7  h9ec563c_2      psi4/osx-64             10MB

  Summary:

  Install: 14 packages

  Total download: 115MB

──────────────────────────────────────────────────────────────────────────

Confirm changes: [Y/n] y
```
which seems to be the same thing you found. It doesn't actually cause a crash on macOS, but we're not supporting Psi4 on macOS and I only checked there because I was lazy.

I don't have Linux on any bare metal at the moment, but in WSL 2 with Ubuntu 18.04 LTS I can install everything using your instructions and reproduce the `ImportError: libecpint.so.1:` crash. When I uninstall and re-install with `conda install -c psi4 -c conda-forge -c defaults psi4`, however, I can run `psi4 --version` without a crash. So I can safely reproduce what you've

Psi4 installation has some rough edges and the docs' strategy of installing it into an existing environment is generally not recommend due to deep conflicts in other packages between `psi4` and `conda-forge` -  whereas one-liners like @pavankum's are often preferred.


I think all stems from a minor oversight in docs. I'll go ahead and fix that. Thanks again for the detailed report - it really makes diagnosing these issues easy.

**Comment by jthorton** [comment]
Docs updated in #184
