### ISSUE TITLE
BaseRecord.extras is optional

### ISSUE THREAD

**Issue by ntBre** [openforcefield/openff-bespokefit#369]
I'm running into an issue where this code is crashing with a `TypeError: argument of type 'NoneType' is not iterable`. Looking at the [qcportal.record_models.BaseRecord](https://github.com/MolSSI/QCFractal/blob/548f72f714640b4fed0d13fa1e7b67eb263def6e/qcportal/qcportal/record_models.py#L372) definition, the `extras` field is optional. 

https://github.com/openforcefield/openff-bespokefit/blob/c9f9054b72ff967f845e40167f5904780e674f5f/openff/bespokefit/optimizers/forcebalance/factories.py#L121

The record causing the issue is a torsion drive record (id 119466792) from my `OpenFF Torsion Coverage Supplement v1.0` dataset:

``` python
from qcportal import PortalClient
client = PortalClient("https://api.qcarchive.molssi.org:443/")
td = client.get_torsiondrives(119466792)
td.id # => 119466792
td.extras is None # => True
client.query_dataset_records(119466792)[0]['dataset_name'] # => 'OpenFF Torsion Coverage Supplement v1.0'
```

 I think an additional condition needs to be added here like `if qc_record.extras and "id" in qc_record.extras`. Again, according to the definition I linked above, the `id` field should also always be present on these records, so this could possibly be simplified to access `qc_record.id` directly, but that seems like a more ambitious change.

I'm also not entirely sure why this has only popped up now. I've been running fits in this environment:

```
$ mamba list 'qcsubmit|bespokefit|qcportal'
# Name                    Version                   Build  Channel
openff-bespokefit         0.2.3+62.g3dde8b5          pypi_0    pypi
openff-qcsubmit           0.52.0             pyhd8ed1ab_0    conda-forge
qcportal                  0.56               pyhd8ed1ab_0    conda-forge
```

and this error happened in this fresh environment:

```
$ mamba list 'qcsubmit|bespokefit|qcportal'
# Name                    Version                   Build  Channel
openff-bespokefit         0.4.0              pyhd8ed1ab_0    conda-forge
openff-qcsubmit           0.53.0             pyhd8ed1ab_1    conda-forge
qcportal                  0.54.1             pyhd8ed1ab_0    conda-forge
```

Obviously I've been using quite an old bespokefit version, but this code hasn't been changed for 3 years, since 0.1.0. I didn't check the blame for the whole call stack, though, so some kind of filter or try/except could have been changed higher up. This record is from a fairly new dataset (~February 2024), but I've still used it in previous fits with my old environment.

**Comment by ntBre** [comment]
After patching the first instance of the error locally,it also pops up on [line 279](https://github.com/openforcefield/openff-bespokefit/blob/c9f9054b72ff967f845e40167f5904780e674f5f/openff/bespokefit/optimizers/forcebalance/factories.py#L279) in the same file.

**Comment by j-wags** [comment]
@ntBre and I discussed this in our check in today - A quick recap:
* @ntBre is right that all current datasets should be assumed to have `qc_record.id` fields populated. However we can't just look only there, since we need to handle both new and old datasets. We're not sure what's up with the old datasets, especially because the different dataset types used to quack very differently, so I'm not sure that we can assume that they'll all have been migrated to have qc_record.id fields populated.
* I think @ntBre's suggestion of using `if qc_record.extras and "id" in qc_record.extras` as a safe way to look before we leap is a good idea. And on top of this, we could even first look at `qc_record.id` before checking anything with `extras`. 
* There's also a bunch of kinda nonsensically structured code from the days when the different QCFractal datasets were structured differently, but since the >0.50 migration this might be redundant and that code could be consolidated in the same PR.

**Comment by ntBre** [comment]
Ah, I think I figured out the `extras` thing [here](https://github.com/openforcefield/openff-bespokefit/blob/c9f9054b72ff967f845e40167f5904780e674f5f/openff/bespokefit/optimizers/forcebalance/factories.py#L152):

```python
            # Assign an id to the **QCElemental** result. This is a dirty way to do
            # this but I can't think of a cleaner way to handle it...
            qc_result.extras["id"] = str(i)
```

The [extras check](https://github.com/openforcefield/openff-bespokefit/commit/e0271255caf7b222bf6ed8b2e0df9537cbf85ae8) was added in a series of commits adding support for local QC data, so datasets from QCA should all have a normal ID, but this is probably still needed for local data and shouldn't be removed.
